
DELAY_BETWEEN_COMMANDS = 1
GAG_MENU = 'UI/Gag_Shop_Menu.PNG'
TU_START_GAG = 'UI/ToonUp_Sart_Gag.PNG'
GAG_MENU_EXIT_BUTTON = 'UI/Done_Buying.PNG'
FRIENDS_BUTTON = 'UI/Friends_Button.PNG'
BATTLE_SYMBOL = "UI/Battle_Symbol.PNG"
GUIDE_BUTTON = "UI/Guide.PNG"
SMILE_SYMBOL = "UI/Healthy.PNG"
COG_BASE_PLATE = "UI/BasePlate.PNG"
BIKE_HORN_PLATE = "Gags/BikeHorn.PNG"
WHISTLE_PLATE = "Gags/Whistle.PNG"
TRUMPET_PLATE = "Gags/Trumpet.PNG"
LOCK_IN_BUTTON = "UI/LOCK.PNG"
TOONUP_LEVEL = 0
TRAP_LEVEL = 0
LURE_LEVEL = 3
SOUND_LEVEL = 3
SQUIRT_LEVEL = 0
ZAP_LEVEL = 3
THROW_LEVEL = 0
DROP_LEVEL = 0

TOONUP_GAGS = [0]
TRAP_GAGS = [0]
LURE_GAGS = [0, 5, 5]
SOUND_GAGS = [0, 10, 5]
SQUIRT_GAGS = [0]
ZAP_GAGS = [0, 0, 5]
THROW_GAGS = [0]
DROP_GAGS = [0]

MyGags = [TOONUP_GAGS, TRAP_GAGS, LURE_GAGS, SOUND_GAGS, SQUIRT_GAGS, ZAP_GAGS, THROW_GAGS, DROP_GAGS]

MyGagLevel = [TOONUP_LEVEL, TRAP_LEVEL, LURE_LEVEL, SOUND_LEVEL, SQUIRT_LEVEL, ZAP_LEVEL, THROW_LEVEL, DROP_LEVEL]

TU_LIMIT = []
TRAP_LIMIT = []
LURE_LIMIT = [15, 10, 5]
SOUND_LIMIT = [15, 10, 5]
SQUIRT_LIMIT = []
ZAP_LIMIT = [15, 10, 5]
THROW_LIMIT = []
DROP_LIMIT = []

GagLevelLimit = [TU_LIMIT, TRAP_LIMIT, LURE_LIMIT, SOUND_LIMIT, SQUIRT_LIMIT, ZAP_LIMIT, THROW_LIMIT, DROP_LIMIT]

GagList = ['ToonUp', 'Trap', 'Lure', 'Sound', 'Squirt', 'Zap', 'Throw', 'Drop']